baseURL: "https://billygrahamram.github.io/" 
title: Billy G. Ram
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

social:
    twitter: billygrahamram

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: /papers/
          weight: 1
        - name: Courses
          url: /courses/
          weight: 2
        # - name: Design
        #   url: /design/
        #   weight: 3
        - name: Tags
          url: /tags/
          weight: 4     
        - name: Sowers
          url: https://sowers.in/
          weight: 3

params:
    description: "I am a researcher currently pursuing my PhD in Precision Agriculture at North Dakota State University."
    author: Billy G. Ram
    # googleAnalyticsID: "G-97G4MZ4061"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Billy G. Ram
          subtitle: "Hey there! I’m a tech enthusiast working as a postdoctoral researcher at North Dakota State University.
          My current research involves hyperspectral imaging, artificial intelligence and precision agriculture. I also work with drones (UAVs), robots and systems for high throughtput phenotyping.
          I believe in building things from scratch that can help the community at large.
          My hobbies are photography, cimematography and anything that can invoke an intellectual thought in me."
          imageUrl: "/picture.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Billy Graham Ram
          buttons:
            - name: Papers
              url: /papers/
            #- name: Courses
              #url: /courses/
            # - name: News
            #   url: /news/
            # - name: Sowers
              # url: "https://sowers.in/"
              # alt: "a non academic venture"
          
    socialIcons:
        - name: CV
          url: /CV_RamBilly.pdf
        - name: Email
          url: mailto:billy.ram@ndsu.edu
        - name: Location
          url: /location/
        - name: Office Hours
          url: /officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=YfPDQ0MAAAAJ&hl=en&authuser=2
        # - name: YouTube
        #   url: https://www.youtube.com/@sowers7102
        - name: GitHub
          url: https://github.com/billygrahamram

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Billy G. Ram"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
